project:
  type: website

website:
  title: "FAIR Research Data Management Workshop"
  page-navigation: true
  page-footer: 
    center: "Developed for the LMU & MPG Open Science Summer School 2024, CCBY4.0"
  reader-mode: false
  repo-url: https://github.com/quarto-dev/quarto-demo
  repo-actions: [edit, issue]
  
  
  navbar:
    left:
      - href: welcome.qmd
        text: Welcome
      - href: about.qmd
        text: About
      
  sidebar:
    style: "floating"
    search: true
    
    contents:
      - section: "0) Welcome"
        href: welcome.qmd
        contents: 
          - text: "Target audience" 
            href: welcome.qmd#who-is-this-workshop-for
          - text: "Benefits"
            href: welcome.qmd#what-is-the-purpose-of-this-workshop
          - text: "Instructions"
            href: welcome.html#how-to
      - section: "1) Organization"
        href: data-organisation.qmd
        contents:
          - text: General notes
            href: data-organisation.qmd#general-notes
          - text: Folder structure
            href: data-organisation.qmd#folder-structure
          - text: File and folder names
            href: data-organisation.qmd#file-and-folder-names
          - text: File formats
            href: data-organisation.qmd#file-formats
      - section: "2) Documentation"
        href: documentation.qmd
        contents:
          - href: documentation.qmd#metadata
            text: Metadata 
          - href: documentation.qmd#readme-file
            text: README file
          - href: documentation.qmd#code-book
            text: Codebook
      - section: "3) Publication"
        href: publication.qmd
        contents: 
          - href: publication.qmd#data-availability-statement
            text: Data Availability Statement
          - href: publication.qmd#license
            text: License
          - href: publication.qmd#persistent-identifier
            text: Persistent identifier
          - href: publication.qmd#repository
            text: Repository
      - section: "4) Data Management Plans"
        href: dmp.qmd
        contents:
          - href: dmp.qmd#general-information
            text: General information
          - href: dmp.qmd#components-of-a-dmp
            text: Components of a DMP
          - href: dmp.qmd#example-data-storage-and-security
            text: Example
          - href: dmp.qmd#why-is-a-dmp-helpful
            text: Why is a DMP helpful?
          - href: dmp.qmd#dmp-tool-rdmo
            text: RDMO
          

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: source

